### ISSUE TITLE
Message isn't customizable, e.g. font, color.

### ISSUE THREAD

**Issue by larryonoff** [ChrisXu1221/CXAlertView#40]

**Comment by ChrisXu1221** [comment]
```Objective-C
- (id)initWithTitle:(NSString *)title message:(NSString *)message cancelButtonTitle:(NSString *)cancelButtonTitle
{
    _vericalPadding = kDefaultVericalPadding;
    _containerWidth = kDefaultContainerWidth;

    UILabel *messageLabel = [[UILabel alloc] init];
    messageLabel.textAlignment = NSTextAlignmentCenter;
    messageLabel.backgroundColor = [UIColor clearColor];
    messageLabel.font = [UIFont systemFontOfSize:14.0];
    messageLabel.textColor = [UIColor blackColor];
    messageLabel.numberOfLines = 0;
    messageLabel.text = message;
    messageLabel.frame = CGRectMake( self.vericalPadding, 0, self.containerWidth - self.vericalPadding*2, [self heightWithText:message font:messageLabel.font]);

    messageLabel.lineBreakMode=LBM;

    return  [self initWithTitle:title contentView:messageLabel cancelButtonTitle:cancelButtonTitle];
}
```

As you can see there is just a label in the alertView, so you can create you own label and make it at the contentView at alertView with `- (id)initWithTitle:(NSString *)title contentView:(UIView *)contentView cancelButtonTitle:(NSString *)cancelButtonTitle;`

**Comment by larryonoff** [comment]
Good point. My assumptions is that since the method **initWithTitle:message:cancelButtonTitle:** is a part of the CXAlertView. It would be complete to have customisation as a part of the CXAlertView.

**Comment by ChrisXu1221** [comment]
Um. Actually the whole concept of this component is to allow anyone to add custom view on the alertView, thus I won't add features for that in case of losing the basic principle.

**Comment by larryonoff** [comment]
Up to you.

By the way **initWithTitle:message:cancelButtonTitle:** uses private method **heightWithText:font**. So **h** file doesn't describe available API entirely. So the control can be used properly only after analysis of **m** file.
